# Site settings
title: Minibrary
description: My Personal Mini Libraryâ™ª
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://entest2.minibrary.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Admin
user_description: 'Engineer @ "Helpdesk / Windows / Linux / Network" Systems'
user_title: 'Engineer @ "Helpdesk / Windows / Linux / Network" Systems'
email: minibrary@gmail.com
twitter_username: minibrary
github_username:  minibrary
gplus_username:  minibrary
disqus_username: minibrary

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# Localization
encoding: utf-8
timezone: Asia/Tokyo
